# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: community
name: keepass
version: 0.1.0
readme: README.md
authors:
  - FILIPPI Lucas (github.com/Luclis)
description: null
license_file: LICENSE
tags:
# tags so people can search for collections https://galaxy.ansible.com/search
# tags are all lower-case, no spaces, no dashes.
  - keepass
  - password
repository: https://github.com/luclis/community.keepass
#documentation: https://github.com/ansible-collection-migration/community.REPO_NAME/tree/main/docs
homepage: https://github.com/luclis/community.keepass
issues: https://github.com/luclis/community.keepass/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#ignoring-files-and-folders
  - .gitignore
  - .github
  - changelogs/.plugin-cache.yaml
  - tests
